### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [GoobyCorp/Xbox-360-Crypto#5]
### Description:

In the "Xbox-360-Crypto/kv_checker.py" and "Xbox-360-Crypto/XeCrypt.py", I have identified security vulnerabilities about insecure cryptographic algorithm. PKCS1v1.5  is vulnerable to the chosen-ciphertext attack. RC4 and DES is no longer considered being secure. Using ECB mode in symmetric cryptographic may cause security vulnerability due to its predictability and lack of diffusion.

### Location:

https://github.com/GoobyCorp/Xbox-360-Crypto/blob/master/XeCrypt.py#L395

```python
self._cipher = Cipher(AES(key), ECB())
```

https://github.com/GoobyCorp/Xbox-360-Crypto/blob/master/XeCrypt.py#L362

```python
self._cipher = Cipher(ARC4(key), None)
```

https://github.com/GoobyCorp/Xbox-360-Crypto/blob/master/kv_checker.py#L118

```python
array_7 = reverse(k.sign(file_time + serial_num + XeCryptSha(rand_key), PKCS1v15(), SHA1()))
```

https://github.com/GoobyCorp/Xbox-360-Crypto/blob/master/xval.py#L42

```python
des = DES.new(des_key, DES.MODE_ECB)
```

### Reference

- **CWE-780: Use of RSA Algorithm without OAEP**
- **CWE-327: Use of a Broken or Risky Cryptographic Algorithm**

### Recommendations:

- Try using other padding(OAEP) instead of PKCS1v1.5.
- Do not use AES-ECB mode. Choose CFB/CTR/OFB mode instead.
- Try using other symmetric encryption algorithm like AES instead of DES, chacha20-poly1305 instead of RC4.

**Comment by GoobyCorp** [comment]
I'm now thoroughly convinced that bots will never replace humans.
